name: toolscosmo
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - cython
  - numpy==1.26.4
  - scipy
  - matplotlib
  - pytest
  - pip
  - pip:
    - .  # This ensures the package and any additional pip dependencies are installed
