name: toolscosmo
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - cython
  - numpy
  - scipy
  - matplotlib
  - astropy
  - pytest
  - scikit-learn==1.2.0
  - tqdm
  - joblib
  - pandas
  - pip:
      - tools21cm
      - -r requirements.txt  # This ensures any additional pip packages are installed
