name: toolscosmo
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - cython
  - numpy==1.26.4
  - scipy
  - matplotlib
  - pytest
  - pip
  - pip:
    - -r requirements.txt  # This ensures any additional pip packages are installed
