name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - master  # Trigger the workflow on push to the master branch
  pull_request:
    branches:
      - master  # Trigger the workflow on pull requests to the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1  # Corrected the version to v1 due to the issue you faced
        with:
          ruby-version: 3.1

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll site
        run: |
          bundle exec jekyll build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: jekyll-site
          path: _site
